[package]
name = "photo_culler"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.3"
egui = "0.33.3"
image = "0.25.9"
kamadak-exif = "0.6.1"
ndarray = "0.17.1"
ort = "2.0.0-rc.10"
rawler = "0.7.1"
rayon = "1.11.0"
redb = "3.1.0"
rustpython = "0.4.0"
tempfile = "3.24.0"
